name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno fmt --check
      - run: deno lint
      - run: echo src/**/*.ts
      - run: deno check src/*.ts
      - run: deno test -A
        env:
          BACKPORTER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BACKPORTER_GITEA_FORK: GiteaBot/gitea
          BACKPORTER_GITHUB_SECRET: dummy
